#ifndef MACRO_CONFIG_INT
#error "The config variables must be included using config_includes.h"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Flags, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Flags, Desc) ;
#endif

MACRO_CONFIG_INT(AmfInputMode, amf_input_mode, 0, 0, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF input prediction mode")
MACRO_CONFIG_INT(AmfFastInputAmount, amf_fast_input_amount, 20, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fast input response in milliseconds")
MACRO_CONFIG_INT(AmfFastInputOthers, amf_fast_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Fast input prediction to other tees")
MACRO_CONFIG_INT(AmfBestInputAmount, amf_best_input_amount, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfBestInputSmoothing, amf_best_input_smoothing, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input smoothing amount")
MACRO_CONFIG_INT(AmfBestInputLatencyComp, amf_best_input_latency_comp, 0, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input latency compensation")
MACRO_CONFIG_INT(AmfBestInputInterpolation, amf_best_input_interpolation, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input interpolation mode")
MACRO_CONFIG_INT(AmfBestInputOthers, amf_best_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Best input prediction to other tees")
MACRO_CONFIG_INT(AmfSaikoInputAmount, amf_saiko_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saiko input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfSaikoInputOthers, amf_saiko_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Saiko input prediction to other tees")
MACRO_CONFIG_INT(AmfSaikoPlusInputAmount, amf_saiko_plus_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saiko+ input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfSaikoPlusInputOthers, amf_saiko_plus_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Saiko+ input prediction to other tees")
MACRO_CONFIG_INT(AmfDeltaInputAmount, amf_delta_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delta input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfDeltaInputOthers, amf_delta_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Delta input prediction to other tees")
MACRO_CONFIG_INT(AmfFInputAmount, amf_f_input_amount, 0, 0, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "F input prediction amount in 0.001 ticks")
MACRO_CONFIG_INT(AmfFInputOthers, amf_f_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply F input prediction to other tees")
MACRO_CONFIG_INT(AmfCloudInputAmount, amf_cloud_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cloud input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfCloudInputOthers, amf_cloud_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Cloud Input prediction to other tees")
MACRO_CONFIG_INT(AmfMeowInputAmount, amf_meow_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Meow input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(AmfMeowInputOthers, amf_meow_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Meow input prediction to other tees")
MACRO_CONFIG_INT(AmfAutoMargin, amf_auto_margin, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically set cl_prediction_margin from network latency and jitter")
MACRO_CONFIG_INT(AmfAutoMarginManualValue, amf_auto_margin_manual_value, 0, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Manual prediction margin preserved by AMF Auto Margin in ms (0 = initialize from cl_prediction_margin)")
MACRO_CONFIG_INT(AmfSnapTap, amf_snap_tap, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Snap Tap for opposite left/right inputs")
MACRO_CONFIG_INT(AmfSnapTapDelay, amf_snap_tap_delay, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Snap Tap direction switch delay in milliseconds (0 = off)")
MACRO_CONFIG_INT(AmfMotionBlurEnabled, amf_motion_blur_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable AMF motion blur")
MACRO_CONFIG_INT(AmfMotionBlur, amf_motion_blur, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of motion blur frame blending (0-100%)")
MACRO_CONFIG_INT(AmfSmoothHud, amf_smooth_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable AMF Client smooth HUD animations")
MACRO_CONFIG_INT(AmfAnimMenu, amf_anim_menu, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate AMF Client menus and popups")
MACRO_CONFIG_INT(AmfAnimStartMenu, amf_anim_start_menu, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate the AMF Client start menu")
MACRO_CONFIG_INT(AmfAnimChatOpen, amf_anim_chat_open, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate opening and closing the chat container")
MACRO_CONFIG_INT(AmfAnimText, amf_anim_text, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate chat text blocks without delaying typing")
MACRO_CONFIG_INT(AmfAnimBlur, amf_anim_blur, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a lightweight background dim for animated AMF UI containers")
MACRO_CONFIG_INT(AmfAnimSlide, amf_anim_slide, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a small slide offset for animated AMF UI containers")
MACRO_CONFIG_INT(AmfAnimDuration, amf_anim_duration, 220, 40, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Base AMF UI animation duration in milliseconds")
MACRO_CONFIG_INT(AmfAnimBlurRadius, amf_anim_blur_radius, 2, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Visual background dim strength for AMF UI animations")
MACRO_CONFIG_INT(AmfAnimSlideDistance, amf_anim_slide_distance, 4, 0, 12, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum AMF UI slide distance in pixels")
MACRO_CONFIG_INT(AmfAnimSmoothCaret, amf_anim_smooth_caret, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smooth the chat text caret visually")
MACRO_CONFIG_INT(AmfAnimCaretSpeed, amf_anim_caret_speed, 75, 10, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat caret approach speed")
MACRO_CONFIG_INT(AmfAnimCaretWidth, amf_anim_caret_width, 1, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat caret width in pixels")
MACRO_CONFIG_INT(AmfAnimChatMessages, amf_anim_chat_messages, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate new chat messages")
MACRO_CONFIG_INT(AmfAnimChatMessageDuration, amf_anim_chat_message_duration, 300, 0, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "New chat message animation duration in milliseconds, zero uses the base duration")
MACRO_CONFIG_INT(AmfAnimScoreboard, amf_anim_scoreboard, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate opening and closing the scoreboard")
MACRO_CONFIG_INT(AmfAnimScoreboardOpenDuration, amf_anim_scoreboard_open_duration, 125, 60, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scoreboard opening animation duration in milliseconds")
MACRO_CONFIG_INT(AmfAnimScoreboardCloseDuration, amf_anim_scoreboard_close_duration, 85, 40, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scoreboard closing animation duration in milliseconds")
MACRO_CONFIG_INT(AmfAnimScoreboardSlideDistance, amf_anim_scoreboard_slide_distance, 12, 0, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scoreboard animation slide distance in pixels")
MACRO_CONFIG_INT(AmfAnimPresetInitialized, amf_anim_preset_initialized, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF animation preset has been initialized")
MACRO_CONFIG_INT(AmfShowClientInfoOnStart, amf_show_client_info_on_start, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the AMF Client agreement on startup")
MACRO_CONFIG_INT(AmfClientInfoAgreementRevision, amf_client_info_agreement_revision, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Last AMF Client agreement revision shown on startup")
MACRO_CONFIG_INT(AmfClientIndicator, amf_client_indicator, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the AMF Client indicator next to local players")
MACRO_CONFIG_INT(AmfClientIndicatorPosition, amf_client_indicator_position, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF Client indicator display mode (0=left, 1=right, 2=hide self locally)")
MACRO_CONFIG_INT(AmfBrowserFilter, amf_browser_filter, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show only servers with active AMF Client users")
MACRO_CONFIG_INT(AmfFancyWeapons, amf_fancy_weapons, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render player rifle and shotgun lasers with the AMF visual effect")
// -1 is a startup-only migration sentinel. It is normalized to one of the
// public modes (0 = off, 1 = T Client) before the first frame and is saved as
// the canonical AMF setting.
MACRO_CONFIG_INT(AmfMovingTilesMode, amf_moving_tiles_mode, -1, -1, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Moving tiles in entities mode (0=off, 1=T Client)")
MACRO_CONFIG_INT(AmfTuneZoneColorPreset, amf_tune_zone_color_preset, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tune zone color preset (0=DDNet blue, 1=red, 2=green, 3=purple)")
// Best Client custom aspect-ratio controls. The mode keeps the legacy -1
// value so profiles created before the setting existed can infer preset mode
// from the stored ratio, exactly like the donor client.
MACRO_CONFIG_INT(AmfCustomAspectRatioMode, amf_custom_aspect_ratio_mode, -1, -1, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio mode (-1=legacy, 0=off, 1=preset, 2=custom)")
MACRO_CONFIG_INT(AmfCustomAspectRatioApplyMode, amf_custom_aspect_ratio_apply_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio apply mode (0=game only, 1=full, 2=game without HUD)")
MACRO_CONFIG_INT(AmfCustomAspectRatio, amf_custom_aspect_ratio, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio multiplied by 100")
MACRO_CONFIG_INT(AmfCustomAspectRatioNum, amf_custom_aspect_ratio_num, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio numerator")
MACRO_CONFIG_INT(AmfCustomAspectRatioDen, amf_custom_aspect_ratio_den, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio denominator")
MACRO_CONFIG_INT(AmfGradientNicknames, amf_gradient_nicknames, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render player nicknames with a gradient")
MACRO_CONFIG_INT(AmfGradientNicknameSource, amf_gradient_nickname_source, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Nickname gradient source (0=skin colors, 1=team/war colors)")
MACRO_CONFIG_INT(AmfGradientCustomSelf, amf_gradient_custom_self, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the custom nickname gradient for local players")
MACRO_CONFIG_INT(AmfGradientShowPlayerCustom, amf_gradient_show_player_custom, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render confirmed AMF players using their published custom nickname gradient")
MACRO_CONFIG_COL(AmfGradientColor1, amf_gradient_color_1, 0xFF3366FFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "First custom nickname gradient color")
MACRO_CONFIG_COL(AmfGradientColor2, amf_gradient_color_2, 0xFF66CCFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Second custom nickname gradient color")
MACRO_CONFIG_INT(AmfGradientTeamColors, amf_gradient_team_colors, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render scoreboard team backgrounds with a gradient")
MACRO_CONFIG_INT(AmfGradientSpectatorMenu, amf_gradient_spectator_menu, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render spectator menu team backgrounds with a gradient")
MACRO_CONFIG_INT(AmfGradientPosition, amf_gradient_position, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient direction (0=left, 1=right)")
MACRO_CONFIG_INT(AmfGradientStrength, amf_gradient_strength, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient strength in percent")
MACRO_CONFIG_INT(AmfFocusMode, amf_focus_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable focus mode to minimize visual distractions")
MACRO_CONFIG_INT(AmfFocusModeHideEmoticons, amf_focus_mode_hide_emoticons, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide emoticon visuals in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideNames, amf_focus_mode_hide_names, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide player names in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideEffects, amf_focus_mode_hide_effects, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide visual effects in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideHud, amf_focus_mode_hide_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide HUD in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideMusicPlayer, amf_focus_mode_hide_music_player, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide music player in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideUi, amf_focus_mode_hide_ui, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide unnecessary UI in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideChat, amf_focus_mode_hide_chat, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide chat in focus mode")
MACRO_CONFIG_INT(AmfFocusModeHideScoreboard, amf_focus_mode_hide_scoreboard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide scoreboard in focus mode")
MACRO_CONFIG_INT(AmfKeyIndicator, amf_key_indicator, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the AMF key indicator")
MACRO_CONFIG_INT(AmfKeyIndicatorShowCps, amf_key_indicator_show_cps, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show clicks per second in the AMF key indicator")
MACRO_CONFIG_INT(AmfKeyIndicatorStyle, amf_key_indicator_style, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF key indicator style (0 = Default, 1 = Minecraft)")
MACRO_CONFIG_INT(AmfKeyIndicatorX, amf_key_indicator_x, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Horizontal position of the AMF key indicator in percent")
MACRO_CONFIG_INT(AmfKeyIndicatorY, amf_key_indicator_y, 31, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vertical position of the AMF key indicator in percent")
MACRO_CONFIG_INT(AmfKeyIndicatorScale, amf_key_indicator_scale, 73, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scale of the AMF key indicator in percent")
MACRO_CONFIG_INT(AmfKeyIndicatorOpacity, amf_key_indicator_opacity, 100, 20, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Opacity of the AMF key indicator in percent")
MACRO_CONFIG_INT(AmfHighPriority, amf_high_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set the AMF Client process priority to High while enabled")
MACRO_CONFIG_INT(AmfDiscordLowPriority, amf_discord_low_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set Discord.exe process priority to Low while enabled")
MACRO_CONFIG_INT(AmfDiscordRPC, amf_discord_rpc, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle AMF Client Discord Rich Presence")
MACRO_CONFIG_INT(AmfPresenceEnabled, amf_presence_enabled, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable the isolated AMF Presence transport")
MACRO_CONFIG_STR(AmfPresenceClientId, amf_presence_client_id, 64, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF Presence installation identifier")
MACRO_CONFIG_STR(AmfPresenceToken, amf_presence_token, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "AMF Presence installation token")
MACRO_CONFIG_STR(AmfPresenceStorageId, amf_presence_storage_id, 65, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hash binding AMF Presence identity to the writable client profile")
MACRO_CONFIG_INT(AmfPresenceDebug, amf_presence_debug, 0, 0, 1, CFGFLAG_CLIENT, "Log AMF Presence diagnostics without credentials")
MACRO_CONFIG_INT(AmfMusicPlayer, amf_music_player, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Music Player HUD element")
MACRO_CONFIG_INT(AmfMusicPlayerShowWhenPaused, amf_music_player_show_when_paused, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep Music Player visible while playback is paused")
MACRO_CONFIG_INT(AmfMusicPlayerVisualizer, amf_music_player_visualizer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable music player visualizer")
MACRO_CONFIG_INT(AmfMusicPlayerVisualizerMode, amf_music_player_visualizer_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer mode")
MACRO_CONFIG_INT(AmfMusicPlayerVisualizerSmoothing, amf_music_player_visualizer_smoothing, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer smoothing")
MACRO_CONFIG_INT(AmfMusicPlayerVisualizerRounding, amf_music_player_visualizer_rounding, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer rounding")
MACRO_CONFIG_INT(AmfMusicPlayerVisualizerColumns, amf_music_player_visualizer_columns, 5, 5, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer bar count")
MACRO_CONFIG_INT(AmfMusicPlayerColorMode, amf_music_player_color_mode, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player color mode (0=static, 1=cover)")
MACRO_CONFIG_COL(AmfMusicPlayerStaticColor, amf_music_player_static_color, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Static music player color")
MACRO_CONFIG_INT(AmfMusicPlayerTextScale, amf_music_player_text_scale, 110, 70, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player text scale")
MACRO_CONFIG_INT(AmfMusicPlayerShowLyrics, amf_music_player_show_lyrics, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show synchronized song lyrics in the music player")
MACRO_CONFIG_INT(AmfMusicPlayerShowCurrentTime, amf_music_player_show_current_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the current time below song lyrics in the music player")
MACRO_CONFIG_INT(AmfMusicPlayerAnimationMs, amf_music_player_animation_ms, 180, 50, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player animation duration")
MACRO_CONFIG_INT(AmfMusicPlayerShowCover, amf_music_player_show_cover, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show music player cover art")
MACRO_CONFIG_INT(AmfMusicPlayerUseColorForHud, amf_music_player_use_color_for_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use music player color for HUD")
MACRO_CONFIG_INT(AmfMusicPlayerHudColorAlpha, amf_music_player_hud_color_alpha, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player HUD color alpha")
MACRO_CONFIG_INT(AmfMusicPlayerDebug, amf_music_player_debug, 0, 0, 2, CFGFLAG_CLIENT, "Music player diagnostics")

// Chat translation
