if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_PULSEAUDIO QUIET libpulse)
  pkg_check_modules(PC_PULSEAUDIO_SIMPLE QUIET libpulse-simple)
endif()

find_library(PULSEAUDIO_LIBRARY
  NAMES pulse
  HINTS ${PC_PULSEAUDIO_LIBDIR} ${PC_PULSEAUDIO_LIBRARY_DIRS}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
find_library(PULSEAUDIO_SIMPLE_LIBRARY
  NAMES pulse-simple
  HINTS ${PC_PULSEAUDIO_SIMPLE_LIBDIR} ${PC_PULSEAUDIO_SIMPLE_LIBRARY_DIRS}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
find_path(PULSEAUDIO_INCLUDEDIR
  NAMES pulse/pulseaudio.h
  HINTS ${PC_PULSEAUDIO_INCLUDEDIR} ${PC_PULSEAUDIO_INCLUDE_DIRS}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PulseAudio DEFAULT_MSG
  PULSEAUDIO_LIBRARY
  PULSEAUDIO_SIMPLE_LIBRARY
  PULSEAUDIO_INCLUDEDIR
)

mark_as_advanced(PULSEAUDIO_LIBRARY PULSEAUDIO_SIMPLE_LIBRARY PULSEAUDIO_INCLUDEDIR)

if(PulseAudio_FOUND)
  # libpulse-simple depends on libpulse, so keep the dependent library first.
  set(PULSEAUDIO_LIBRARIES ${PULSEAUDIO_SIMPLE_LIBRARY} ${PULSEAUDIO_LIBRARY})
  set(PULSEAUDIO_INCLUDE_DIRS ${PULSEAUDIO_INCLUDEDIR} ${PC_PULSEAUDIO_INCLUDE_DIRS})
endif()
